'use client'

import { useRoster } from '@/lib/roster-context'
import { CAP_THRESHOLDS, formatCurrency } from '@/lib/data'
import { getTeamCapState } from '@/lib/team-cap-state'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { cn } from '@/lib/utils'
import { Season } from '@/lib/types'

const SEASON: Season = '2026-27'
const MS_PER_DAY = 1000 * 60 * 60 * 24
const SOON_THRESHOLD_DAYS = 30

function daysRemaining(expires: string): number {
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  const expiry = new Date(expires)
  expiry.setHours(0, 0, 0, 0)
  return Math.round((expiry.getTime() - today.getTime()) / MS_PER_DAY)
}

// TPEs are generally usable at any apron level — unlike cash, apron status
// doesn't block them outright. The two apron-specific effects: at/above the
// first apron a TPE loses its $250K cushion (immaterial here) and, more
// importantly, a TPE generated before the *previous* trade deadline becomes
// unusable. Approximating that deadline as Feb 1 of the season's start year
// (the app doesn't source exact deadline dates), and approximating each
// TPE's creation date as one year before its expiration (TPEs are 1-year-lived).
function priorSeasonDeadlineCutoff(season: Season): Date {
  const startYear = parseInt(season.split('-')[0], 10)
  return new Date(startYear, 1, 1) // Feb 1
}

function tpeGeneratedDate(expires: string): Date {
  const d = new Date(expires)
  d.setFullYear(d.getFullYear() - 1)
  return d
}

export function TradeExceptionsPanel() {
  const { selectedTeam, selectedTeamAbbr, getTeamCapTotal } = useRoster()
  const { apronTotal } = getTeamCapTotal(selectedTeamAbbr, SEASON)
  const capState = getTeamCapState(selectedTeamAbbr, SEASON)

  const thresholds = CAP_THRESHOLDS[SEASON]
  const firstApron = thresholds.find((t) => t.type === 'first-apron')?.value ?? 0
  const secondApron = thresholds.find((t) => t.type === 'second-apron')?.value ?? 0
  const overFirstApron = apronTotal >= firstApron
  const overSecondApron = apronTotal >= secondApron
  const apronTierLabel = overSecondApron ? '2nd Apron' : overFirstApron ? '1st Apron' : 'Below 1st Apron'

  const deadlineCutoff = priorSeasonDeadlineCutoff(SEASON)

  const heldTPEs = (capState?.heldTPEs ?? [])
    .filter((tpe) => daysRemaining(tpe.expires) >= 0)
    .map((tpe) => ({
      ...tpe,
      locked: overFirstApron && tpeGeneratedDate(tpe.expires) < deadlineCutoff,
    }))
    .sort((a, b) => daysRemaining(a.expires) - daysRemaining(b.expires))

  const cashLedger = capState?.cashLedger

  return (
    <Card className="border border-border rounded-lg overflow-hidden shadow-none py-0 gap-0">
      <CardHeader className="py-2.5 px-3.5 gap-0 bg-accent">
        <div className="flex items-center justify-between">
          <CardTitle className="text-[12.5px] font-semibold">Trade Exceptions (26-27)</CardTitle>
          <span
            className={cn(
              'text-[10.5px] font-semibold px-1.5 py-0.5 rounded',
              overSecondApron
                ? 'bg-red-500/15 text-red-500'
                : overFirstApron
                  ? 'bg-amber-500/15 text-amber-500'
                  : 'bg-muted text-muted-foreground'
            )}
          >
            {apronTierLabel}
          </span>
        </div>
      </CardHeader>
      <CardContent className="px-3.5 py-3">
        {/* Held TPEs */}
        <div>
          <p className="text-[10.5px] font-semibold text-muted-foreground uppercase tracking-wide mb-1.5">
            Held Trade Exceptions
          </p>
          {heldTPEs.length === 0 ? (
            <p className="text-xs text-muted-foreground">No active trade exceptions.</p>
          ) : (
            <div className="grid grid-cols-1 gap-2">
              {heldTPEs.map((tpe) => {
                const remaining = daysRemaining(tpe.expires)
                const soon = remaining <= SOON_THRESHOLD_DAYS
                return (
                  <div key={tpe.id} className="flex items-center justify-between">
                    <div className="min-w-0">
                      <div className={cn('text-xs font-medium', tpe.locked && 'text-amber-500')}>
                        {formatCurrency(tpe.amount)} remaining balance
                        {tpe.locked && ' · Locked'}
                      </div>
                      <div className="text-[10.5px] text-muted-foreground truncate">
                        {tpe.fromPlayer ? `From: ${tpe.fromPlayer}` : 'Generated by trade'}
                        {tpe.locked && ' — pre-existing exception, unusable above the 1st apron'}
                      </div>
                    </div>
                    <div className="text-right shrink-0 pl-2">
                      <div className={cn('text-xs font-medium', soon ? 'text-amber-500' : 'text-foreground')}>
                        {remaining}d left
                      </div>
                      <div className="text-[10.5px] text-muted-foreground">
                        {new Date(tpe.expires).toLocaleDateString('en-US', {
                          month: 'short',
                          day: 'numeric',
                          year: 'numeric',
                        })}
                      </div>
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </div>

        {/* Cash Ledger */}
        <div className="mt-3 pt-3 border-t border-border">
          <p className="text-[10.5px] font-semibold text-muted-foreground uppercase tracking-wide mb-1.5">
            Cash in Trades
          </p>
          {cashLedger === undefined ? (
            <p className="text-xs text-muted-foreground">N/A — not tracked for future seasons.</p>
          ) : (
            <div className="grid grid-cols-2 gap-2">
              <div>
                <div className="text-[10.5px] text-muted-foreground">Available to Send</div>
                {overSecondApron ? (
                  <div className="text-xs font-medium text-amber-500">Restricted (2nd apron)</div>
                ) : (
                  <div className="text-xs font-medium">{formatCurrency(cashLedger.availableToSend)}</div>
                )}
              </div>
              <div>
                <div className="text-[10.5px] text-muted-foreground">Available to Receive</div>
                <div className="text-xs font-medium">{formatCurrency(cashLedger.availableToReceive)}</div>
              </div>
            </div>
          )}
        </div>

        <p className="text-[10.5px] text-muted-foreground mt-2.5 pt-2.5 border-t border-border">
          TPEs and cash don&apos;t count toward Team Salary — they&apos;re separate tools for absorbing money in a
          deal, not extra cap room.
          {overFirstApron
            ? ` At/above the first apron, ${selectedTeam.name} loses the matching cushion (100% dollar-for-dollar) and can't use TPEs generated before the prior trade deadline — those are flagged Locked above.`
            : ''}{' '}
          Cash-send/receive balances are tracked separately and don&apos;t offset each other. TPE lock dates are
          approximated from each exception&apos;s 1-year expiration, not sourced deadline data.
        </p>
      </CardContent>
    </Card>
  )
}
