'use client'

import { useRoster } from '@/lib/roster-context'
import { CAP_THRESHOLDS, formatCurrency } from '@/lib/data'
import { getTeamCapState } from '@/lib/team-cap-state'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { cn } from '@/lib/utils'
import { Season } from '@/lib/types'

const SEASON: Season = '2026-27'
const MS_PER_DAY = 1000 * 60 * 60 * 24
const SOON_THRESHOLD_DAYS = 30

function daysRemaining(expires: string): number {
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  const expiry = new Date(expires)
  expiry.setHours(0, 0, 0, 0)
  return Math.round((expiry.getTime() - today.getTime()) / MS_PER_DAY)
}

export function TradeExceptionsPanel() {
  const { selectedTeam, selectedTeamAbbr, getTeamCapTotal } = useRoster()
  const { apronTotal } = getTeamCapTotal(selectedTeamAbbr, SEASON)
  const capState = getTeamCapState(selectedTeamAbbr, SEASON)

  const thresholds = CAP_THRESHOLDS[SEASON]
  const secondApron = thresholds.find((t) => t.type === 'second-apron')?.value ?? 0
  const overSecondApron = apronTotal >= secondApron

  const heldTPEs = (capState?.heldTPEs ?? [])
    .filter((tpe) => daysRemaining(tpe.expires) >= 0)
    .sort((a, b) => daysRemaining(a.expires) - daysRemaining(b.expires))

  const cashLedger = capState?.cashLedger

  return (
    <Card className="border border-border rounded-lg overflow-hidden shadow-none py-0 gap-0">
      <CardHeader className="py-2.5 px-3.5 gap-0 bg-accent">
        <div className="flex items-center justify-between">
          <CardTitle className="text-[12.5px] font-semibold">Trade Exceptions (26-27)</CardTitle>
        </div>
      </CardHeader>
      <CardContent className="px-3.5 py-3">
        {/* Held TPEs */}
        <div>
          <p className="text-[10.5px] font-semibold text-muted-foreground uppercase tracking-wide mb-1.5">
            Held Trade Exceptions
          </p>
          {heldTPEs.length === 0 ? (
            <p className="text-xs text-muted-foreground">No active trade exceptions.</p>
          ) : (
            <div className="grid grid-cols-1 gap-2">
              {heldTPEs.map((tpe) => {
                const remaining = daysRemaining(tpe.expires)
                const soon = remaining <= SOON_THRESHOLD_DAYS
                return (
                  <div key={tpe.id} className="flex items-center justify-between">
                    <div className="min-w-0">
                      <div className="text-xs font-medium">{formatCurrency(tpe.amount)} remaining balance</div>
                      <div className="text-[10.5px] text-muted-foreground truncate">
                        {tpe.fromPlayer ? `From: ${tpe.fromPlayer}` : 'Generated by trade'}
                      </div>
                    </div>
                    <div className="text-right shrink-0 pl-2">
                      <div className={cn('text-xs font-medium', soon ? 'text-amber-500' : 'text-foreground')}>
                        {remaining}d left
                      </div>
                      <div className="text-[10.5px] text-muted-foreground">
                        {new Date(tpe.expires).toLocaleDateString('en-US', {
                          month: 'short',
                          day: 'numeric',
                          year: 'numeric',
                        })}
                      </div>
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </div>

        {/* Cash Ledger */}
        <div className="mt-3 pt-3 border-t border-border">
          <p className="text-[10.5px] font-semibold text-muted-foreground uppercase tracking-wide mb-1.5">
            Cash in Trades
          </p>
          {cashLedger === undefined ? (
            <p className="text-xs text-muted-foreground">N/A — not tracked for future seasons.</p>
          ) : (
            <div className="grid grid-cols-2 gap-2">
              <div>
                <div className="text-[10.5px] text-muted-foreground">Available to Send</div>
                {overSecondApron ? (
                  <div className="text-xs font-medium text-amber-500">Restricted (2nd apron)</div>
                ) : (
                  <div className="text-xs font-medium">{formatCurrency(cashLedger.availableToSend)}</div>
                )}
              </div>
              <div>
                <div className="text-[10.5px] text-muted-foreground">Available to Receive</div>
                <div className="text-xs font-medium">{formatCurrency(cashLedger.availableToReceive)}</div>
              </div>
            </div>
          )}
        </div>

        <p className="text-[10.5px] text-muted-foreground mt-2.5 pt-2.5 border-t border-border">
          TPEs and cash don&apos;t count toward Team Salary — they&apos;re separate tools for absorbing money in a
          deal, not extra cap room. TPE usability depends on the current apron status of the {selectedTeam.name}{' '}
          (not checked here). Cash-send/receive balances are tracked separately and don&apos;t offset each other.
        </p>
      </CardContent>
    </Card>
  )
}
