import { Player, Season, SEASONS } from './types'

export type DraftRound = 'First Round' | 'Second Round'

export interface DraftPick {
  teamOwner: string
  year: number
  round: DraftRound
  teamFrom: string | null
  swapOwner: string | null
  swapOption: string | null
  protections: string | null
  pickNumber: number | null
  pickPool: string | null
  rank: string | null
}

// Team name to abbreviation mapping
const TEAM_NAME_TO_ABBR: Record<string, string> = {
  'Atlanta Hawks': 'ATL',
  'Boston Celtics': 'BOS',
  'Brooklyn Nets': 'BRK',
  'Charlotte Hornets': 'CHO',
  'Chicago Bulls': 'CHI',
  'Cleveland Cavaliers': 'CLE',
  'Dallas Mavericks': 'DAL',
  'Denver Nuggets': 'DEN',
  'Detroit Pistons': 'DET',
  'Golden State Warriors': 'GSW',
  'Houston Rockets': 'HOU',
  'Indiana Pacers': 'IND',
  'Los Angeles Clippers': 'LAC',
  'Los Angeles Lakers': 'LAL',
  'Memphis Grizzlies': 'MEM',
  'Miami Heat': 'MIA',
  'Milwaukee Bucks': 'MIL',
  'Minnesota Timberwolves': 'MIN',
  'New Orleans Pelicans': 'NOP',
  'New York Knicks': 'NYK',
  'Oklahoma City Thunder': 'OKC',
  'Orlando Magic': 'ORL',
  'Philadelphia Sixers': 'PHI',
  'Phoenix Suns': 'PHO',
  'Portland Trail Blazers': 'POR',
  'Sacramento Kings': 'SAC',
  'San Antonio Spurs': 'SAS',
  'Toronto Raptors': 'TOR',
  'Utah Jazz': 'UTA',
  'Washington Wizards': 'WAS',
}

export const DRAFT_PICKS: DraftPick[] = [
  { teamOwner: 'Atlanta Hawks', year: 2026, round: 'First Round', teamFrom: 'New Orleans Pelicans', swapOwner: null, swapOption: null, protections: null, pickNumber: 8, pickPool: null, rank: null },
  { teamOwner: 'Atlanta Hawks', year: 2026, round: 'First Round', teamFrom: 'Cleveland Cavaliers', swapOwner: null, swapOption: null, protections: null, pickNumber: 23, pickPool: null, rank: null },
  { teamOwner: 'Atlanta Hawks', year: 2026, round: 'Second Round', teamFrom: 'Boston Celtics', swapOwner: null, swapOption: null, protections: null, pickNumber: 57, pickPool: null, rank: null },
  { teamOwner: 'Atlanta Hawks', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Atlanta Hawks', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Atlanta Hawks', year: 2029, round: 'Second Round', teamFrom: 'Cleveland Cavaliers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Atlanta Hawks', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Atlanta Hawks', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Atlanta Hawks', year: 2030, round: 'Second Round', teamFrom: 'New York Knicks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Atlanta Hawks', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Atlanta Hawks', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: 'Houston Rockets', swapOption: null, protections: '56-60 to Boston Celtics', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Atlanta Hawks', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Atlanta Hawks', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Atlanta Hawks', year: 2032, round: 'Second Round', teamFrom: 'Los Angeles Lakers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Atlanta Hawks', year: 2027, round: 'First Round', teamFrom: null, swapOwner: 'Milwaukee Bucks, New Orleans Pelicans', swapOption: null, protections: 'if either or both 5-30', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Atlanta Hawks', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'ATL, CLE, UTH', rank: 'More favorable of ATL vs (less favorable of CLE/UTH)' },
  { teamOwner: 'Boston Celtics', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 27, pickPool: null, rank: null },
  { teamOwner: 'Boston Celtics', year: 2026, round: 'Second Round', teamFrom: 'Milwaukee Bucks', swapOwner: null, swapOption: null, protections: null, pickNumber: 40, pickPool: null, rank: null },
  { teamOwner: 'Boston Celtics', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Boston Celtics', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Boston Celtics', year: 2030, round: 'Second Round', teamFrom: 'Charlotte Hornets', swapOwner: null, swapOption: null, protections: '56-60', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Boston Celtics', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Boston Celtics', year: 2031, round: 'Second Round', teamFrom: 'Houston Rockets', swapOwner: null, swapOption: null, protections: '56-60', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Boston Celtics', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Boston Celtics', year: 2028, round: 'First Round', teamFrom: null, swapOwner: 'San Antonio Spurs', swapOption: null, protections: '1', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Boston Celtics', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: 'Frozen through 2027-28', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Boston Celtics', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'BOS, CLE', rank: 'Less favorable' },
  { teamOwner: 'Brooklyn Nets', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 6, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2026, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 33, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2026, round: 'Second Round', teamFrom: 'Los Angeles Clippers', swapOwner: null, swapOption: null, protections: null, pickNumber: 43, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2027, round: 'First Round', teamFrom: null, swapOwner: 'Houston Rockets', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2027, round: 'First Round', teamFrom: 'New York Knicks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2028, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2028, round: 'Second Round', teamFrom: 'Atlanta Hawks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2028, round: 'Second Round', teamFrom: 'Memphis Grizzlies', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2029, round: 'First Round', teamFrom: 'New York Knicks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2029, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2029, round: 'Second Round', teamFrom: 'Dallas Mavericks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2029, round: 'Second Round', teamFrom: 'Golden State Warriors', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2029, round: 'Second Round', teamFrom: 'Memphis Grizzlies', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2030, round: 'Second Round', teamFrom: 'Boston Celtics', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2030, round: 'Second Round', teamFrom: 'Dallas Mavericks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2030, round: 'Second Round', teamFrom: 'Los Angeles Lakers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2031, round: 'First Round', teamFrom: 'New York Knicks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2031, round: 'Second Round', teamFrom: 'Los Angeles Lakers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2032, round: 'First Round', teamFrom: 'Denver Nuggets', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2032, round: 'Second Round', teamFrom: 'Denver Nuggets', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2032, round: 'Second Round', teamFrom: 'Miami Heat', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2032, round: 'Second Round', teamFrom: 'Toronto Raptors', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2028, round: 'First Round', teamFrom: 'Philadelphia Sixers', swapOwner: null, swapOption: null, protections: 'if PHL 1-8 in 2028', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2029, round: 'First Round', teamFrom: null, swapOwner: 'Dallas Mavericks, Phoenix Suns, Houston Rockets', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Brooklyn Nets', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'BRK, PHL 9-30, PHX, NYK', rank: 'Most and 3rd most (if PHL 9-30 is 3rd most and NYK is most/2nd most); otherwise most / two most' },
  { teamOwner: 'Brooklyn Nets', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'BRK, PHX, NYK', rank: 'Complement of: least favorable to NYK (if NYK and/or PHL 9-30 less favorable than BRK/PHX); otherwise 2nd most favorable to NYK' },
  { teamOwner: 'Charlotte Hornets', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 14, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2026, round: 'First Round', teamFrom: 'Orlando Magic', swapOwner: null, swapOption: null, protections: null, pickNumber: 18, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2027, round: 'First Round', teamFrom: 'Dallas Mavericks', swapOwner: null, swapOption: null, protections: '3-30', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2027, round: 'First Round', teamFrom: 'Miami Heat', swapOwner: null, swapOption: null, protections: '15-30', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2028, round: 'Second Round', teamFrom: 'Orlando Magic', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2029, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2031, round: 'Second Round', teamFrom: 'Milwaukee Bucks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2031, round: 'Second Round', teamFrom: 'Phoenix Suns', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2032, round: 'Second Round', teamFrom: 'Milwaukee Bucks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2027, round: 'First Round', teamFrom: 'Dallas Mavericks', swapOwner: null, swapOption: null, protections: '1-2 to Dallas Mavericks', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2027, round: 'First Round', teamFrom: 'Miami Heat', swapOwner: null, swapOption: null, protections: '1-14 to Miami Heat', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: '56-60 to Boston Celtics', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: 'Boston Celtics, Orlando Magic', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: 'Portland Trail Blazers, New Orleans Pelicans', protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2029, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: 'Atlanta Hawks, Miami Heat', protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: 'Utah Jazz, Los Angeles Clippers', protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2028, round: 'First Round', teamFrom: 'Miami Heat', swapOwner: null, swapOption: null, protections: 'if not already settled', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2028, round: 'Second Round', teamFrom: 'Miami Heat', swapOwner: null, swapOption: null, protections: 'if DAL does not convey 1st round pick to CHA in 2027', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2029, round: 'Second Round', teamFrom: 'Denver Nuggets', swapOwner: null, swapOption: null, protections: 'if DEN has conveyed a first potential 1st round pick to OKC by 2029', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2029, round: 'First Round', teamFrom: null, swapOwner: 'Utah Jazz, Cleveland Cavaliers, Minnesota Timberwolves', swapOption: null, protections: 'MIN 6-30', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Charlotte Hornets', year: 2028, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'CHA, LAC', rank: 'More favorable' },
  { teamOwner: 'Chicago Bulls', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 4, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2026, round: 'First Round', teamFrom: 'Portland Trail Blazers', swapOwner: null, swapOption: null, protections: null, pickNumber: 15, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2026, round: 'Second Round', teamFrom: 'New Orleans Pelicans', swapOwner: null, swapOption: null, protections: null, pickNumber: 38, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2026, round: 'Second Round', teamFrom: 'Denver Nuggets', swapOwner: null, swapOption: null, protections: null, pickNumber: 56, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2027, round: 'Second Round', teamFrom: 'Cleveland Cavaliers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2028, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2029, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2031, round: 'Second Round', teamFrom: 'Denver Nuggets', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2031, round: 'Second Round', teamFrom: 'New York Knicks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: 'Minnesota Timberwolves, Golden State Warriors', protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: 'Phoenix Suns, Houston Rockets', protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Chicago Bulls', year: 2029, round: 'Second Round', teamFrom: null, swapOwner: 'Detroit Pistons, Milwaukee Bucks, New York Knicks', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Cleveland Cavaliers', year: 2026, round: 'First Round', teamFrom: 'San Antonio Spurs', swapOwner: null, swapOption: null, protections: null, pickNumber: 29, pickPool: null, rank: null },
  { teamOwner: 'Cleveland Cavaliers', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Cleveland Cavaliers', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Cleveland Cavaliers', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Cleveland Cavaliers', year: 2028, round: 'First Round', teamFrom: null, swapOwner: 'Utah Jazz, Atlanta Hawks', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 9, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2026, round: 'First Round', teamFrom: 'Oklahoma City Thunder', swapOwner: null, swapOption: null, protections: null, pickNumber: 30, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2026, round: 'Second Round', teamFrom: 'Phoenix Suns', swapOwner: null, swapOption: null, protections: null, pickNumber: 48, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2027, round: 'Second Round', teamFrom: 'Chicago Bulls', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2028, round: 'First Round', teamFrom: null, swapOwner: 'Oklahoma City Thunder', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2029, round: 'First Round', teamFrom: 'Los Angeles Lakers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2029, round: 'Second Round', teamFrom: 'Houston Rockets', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2030, round: 'First Round', teamFrom: null, swapOwner: 'San Antonio Spurs', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2030, round: 'First Round', teamFrom: 'Golden State Warriors', swapOwner: null, swapOption: null, protections: '21-30', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2030, round: 'Second Round', teamFrom: 'Philadelphia Sixers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: '3-30 to Charlotte Hornets', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2030, round: 'First Round', teamFrom: 'Golden State Warriors', swapOwner: null, swapOption: null, protections: '1-20 to Golden State Warriors', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Dallas Mavericks', year: 2030, round: 'Second Round', teamFrom: 'Golden State Warriors', swapOwner: null, swapOption: null, protections: 'if GOS does not convey 1st round pick to DAL in 2030', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Denver Nuggets', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 26, pickPool: null, rank: null },
  { teamOwner: 'Denver Nuggets', year: 2026, round: 'Second Round', teamFrom: 'Atlanta Hawks', swapOwner: null, swapOption: null, protections: null, pickNumber: 49, pickPool: null, rank: null },
  { teamOwner: 'Denver Nuggets', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Denver Nuggets', year: 2028, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: '34-60 to Washington Wizards', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Denver Nuggets', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'DEN 6-30, OKC, LAC', rank: 'Two most / more favorable, to OKC' },
  { teamOwner: 'Detroit Pistons', year: 2026, round: 'First Round', teamFrom: 'Minnesota Timberwolves', swapOwner: null, swapOption: null, protections: null, pickNumber: 21, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2027, round: 'Second Round', teamFrom: 'Milwaukee Bucks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2028, round: 'Second Round', teamFrom: 'New York Knicks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2030, round: 'Second Round', teamFrom: 'Minnesota Timberwolves', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2031, round: 'Second Round', teamFrom: 'Dallas Mavericks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: 'Brooklyn Nets, Dallas Mavericks', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: 'Golden State Warriors, Minnesota Timberwolves', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2028, round: 'Second Round', teamFrom: 'Miami Heat', swapOwner: null, swapOption: null, protections: 'if DAL conveys 1st round pick to CHA in 2027', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2028, round: 'Second Round', teamFrom: null, swapOwner: 'Charlotte Hornets, Los Angeles Clippers', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Detroit Pistons', year: 2029, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'DET, MIL, NYK', rank: 'Two most favorable' },
  { teamOwner: 'Golden State Warriors', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 11, pickPool: null, rank: null },
  { teamOwner: 'Golden State Warriors', year: 2026, round: 'Second Round', teamFrom: 'Los Angeles Lakers', swapOwner: null, swapOption: null, protections: null, pickNumber: 54, pickPool: null, rank: null },
  { teamOwner: 'Golden State Warriors', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Golden State Warriors', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Golden State Warriors', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Golden State Warriors', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Golden State Warriors', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Golden State Warriors', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: '21-30 to Dallas Mavericks', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Golden State Warriors', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: '51-60 to Memphis Grizzlies', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Houston Rockets', year: 2026, round: 'Second Round', teamFrom: 'Chicago Bulls', swapOwner: null, swapOption: null, protections: null, pickNumber: 39, pickPool: null, rank: null },
  { teamOwner: 'Houston Rockets', year: 2026, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 53, pickPool: null, rank: null },
  { teamOwner: 'Houston Rockets', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: 'Brooklyn Nets', protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Houston Rockets', year: 2027, round: 'First Round', teamFrom: 'Phoenix Suns', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Houston Rockets', year: 2027, round: 'Second Round', teamFrom: 'Memphis Grizzlies', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Houston Rockets', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Houston Rockets', year: 2028, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Houston Rockets', year: 2029, round: 'Second Round', teamFrom: 'Sacramento Kings', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Houston Rockets', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Houston Rockets', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Houston Rockets', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Houston Rockets', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: 'Atlanta Hawks', swapOption: null, protections: '56-60 to Boston Celtics', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Houston Rockets', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: 'Portland Trail Blazers, New Orleans Pelicans', swapOption: null, protections: 'if 56-60', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Houston Rockets', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'HOU, DAL, PHX', rank: 'Two most favorable' },
  { teamOwner: 'Indiana Pacers', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Indiana Pacers', year: 2027, round: 'Second Round', teamFrom: 'Utah Jazz', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Indiana Pacers', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Indiana Pacers', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Indiana Pacers', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Indiana Pacers', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Indiana Pacers', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Indiana Pacers', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Indiana Pacers', year: 2028, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'IND, PHX', rank: 'More favorable' },
  { teamOwner: 'Indiana Pacers', year: 2029, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'IND, WAS', rank: 'More favorable' },
  { teamOwner: 'Indiana Pacers', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'IND, MIA, MEM', rank: 'Least favorable' },
  { teamOwner: 'Los Angeles Clippers', year: 2026, round: 'First Round', teamFrom: 'Indiana Pacers', swapOwner: null, swapOption: null, protections: null, pickNumber: 5, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Clippers', year: 2026, round: 'Second Round', teamFrom: 'Memphis Grizzlies', swapOwner: null, swapOption: null, protections: null, pickNumber: 36, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Clippers', year: 2026, round: 'Second Round', teamFrom: 'Cleveland Cavaliers', swapOwner: null, swapOption: null, protections: null, pickNumber: 52, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Clippers', year: 2028, round: 'Second Round', teamFrom: 'Dallas Mavericks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Clippers', year: 2029, round: 'First Round', teamFrom: 'Indiana Pacers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Clippers', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Clippers', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Clippers', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Clippers', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Clippers', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Clippers', year: 2029, round: 'First Round', teamFrom: null, swapOwner: 'Philadelphia Sixers', swapOption: null, protections: '1-3', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Clippers', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'LAC, DEN 6-30, OKC', rank: 'Least/less favorable' },
  { teamOwner: 'Los Angeles Lakers', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 25, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Lakers', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Lakers', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Lakers', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Lakers', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Los Angeles Lakers', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: '5-30 to Memphis Grizzlies', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 3, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2026, round: 'First Round', teamFrom: 'Phoenix Suns', swapOwner: null, swapOption: null, protections: null, pickNumber: 16, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2026, round: 'Second Round', teamFrom: 'Indiana Pacers', swapOwner: null, swapOption: null, protections: null, pickNumber: 32, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2027, round: 'First Round', teamFrom: 'Los Angeles Lakers', swapOwner: null, swapOption: null, protections: '5-30', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2029, round: 'First Round', teamFrom: null, swapOwner: 'Orlando Magic', swapOption: null, protections: '1-2', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2029, round: 'Second Round', teamFrom: 'Portland Trail Blazers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2030, round: 'First Round', teamFrom: 'Orlando Magic', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2031, round: 'First Round', teamFrom: 'Phoenix Suns', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: 'Philadelphia Sixers', protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2032, round: 'Second Round', teamFrom: 'Golden State Warriors', swapOwner: null, swapOption: null, protections: '51-60', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2032, round: 'Second Round', teamFrom: 'Golden State Warriors', swapOwner: null, swapOption: null, protections: '31-50 to Golden State Warriors', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2027, round: 'First Round', teamFrom: 'Los Angeles Lakers', swapOwner: null, swapOption: null, protections: '1-4 to Los Angeles Lakers', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: '51-60 to Minnesota Timberwolves', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2027, round: 'Second Round', teamFrom: 'Los Angeles Lakers', swapOwner: null, swapOption: null, protections: 'if LAL does not convey 1st round pick to MEM in 2027', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2029, round: 'Second Round', teamFrom: 'Orlando Magic', swapOwner: null, swapOption: null, protections: 'if ORL 1-2 in 2029', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Memphis Grizzlies', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'MEM, PHX, WAS', rank: 'More favorable of MEM vs (less favorable of PHX/WAS)' },
  { teamOwner: 'Memphis Grizzlies', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'MEM, IND, MIA', rank: 'More favorable of MEM vs (less favorable of IND/MIA)' },
  { teamOwner: 'Miami Heat', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 13, pickPool: null, rank: null },
  { teamOwner: 'Miami Heat', year: 2026, round: 'Second Round', teamFrom: 'Golden State Warriors', swapOwner: null, swapOption: null, protections: null, pickNumber: 41, pickPool: null, rank: null },
  { teamOwner: 'Miami Heat', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Miami Heat', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Miami Heat', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Miami Heat', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Miami Heat', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: '15-30 to Charlotte Hornets', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Miami Heat', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: 'Oklahoma City Thunder, Houston Rockets, Indiana Pacers, San Antonio Spurs', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Milwaukee Bucks', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 10, pickPool: null, rank: null },
  { teamOwner: 'Milwaukee Bucks', year: 2030, round: 'First Round', teamFrom: null, swapOwner: 'Portland Trail Blazers', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Milwaukee Bucks', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Milwaukee Bucks', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Milwaukee Bucks', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'MIL, POR, WAS, BRK, PHL 9-30, PHX', rank: 'Less favorable of (less favorable of MIL/POR) vs (more favorable of WAS and least/less favorable of BRK/PHL 9-30/PHX)' },
  { teamOwner: 'Minnesota Timberwolves', year: 2026, round: 'First Round', teamFrom: 'Detroit Pistons', swapOwner: null, swapOption: null, protections: null, pickNumber: 28, pickPool: null, rank: null },
  { teamOwner: 'Minnesota Timberwolves', year: 2026, round: 'Second Round', teamFrom: 'San Antonio Spurs', swapOwner: null, swapOption: null, protections: null, pickNumber: 59, pickPool: null, rank: null },
  { teamOwner: 'Minnesota Timberwolves', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Minnesota Timberwolves', year: 2030, round: 'Second Round', teamFrom: 'Memphis Grizzlies', swapOwner: null, swapOption: null, protections: '51-60', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Minnesota Timberwolves', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Minnesota Timberwolves', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: 'Frozen through 2027-28', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Minnesota Timberwolves', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'MIN 6-30, CLE, UTH', rank: 'Most / two most favorable, to UTH' },
  { teamOwner: 'Minnesota Timberwolves', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'MIN 2-30, SAN, DAL', rank: 'Less favorable of MIN 2-30 vs (more favorable of SAN/DAL)' },
  { teamOwner: 'New Orleans Pelicans', year: 2026, round: 'Second Round', teamFrom: 'Detroit Pistons', swapOwner: null, swapOption: null, protections: null, pickNumber: 58, pickPool: null, rank: null },
  { teamOwner: 'New Orleans Pelicans', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'New Orleans Pelicans', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'New Orleans Pelicans', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'New Orleans Pelicans', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: 'Orlando Magic', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'New Orleans Pelicans', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'New Orleans Pelicans', year: 2031, round: 'Second Round', teamFrom: 'Toronto Raptors', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'New Orleans Pelicans', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'New Orleans Pelicans', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'New Orleans Pelicans', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'NOP, MIL', rank: 'More favorable' },
  { teamOwner: 'New Orleans Pelicans', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'OKC, HOU, IND, MIA', rank: '2nd most favorable' },
  { teamOwner: 'New York Knicks', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 24, pickPool: null, rank: null },
  { teamOwner: 'New York Knicks', year: 2026, round: 'Second Round', teamFrom: 'Washington Wizards', swapOwner: null, swapOption: null, protections: null, pickNumber: 31, pickPool: null, rank: null },
  { teamOwner: 'New York Knicks', year: 2026, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 55, pickPool: null, rank: null },
  { teamOwner: 'New York Knicks', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'New York Knicks', year: 2027, round: 'Second Round', teamFrom: 'Washington Wizards', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'New York Knicks', year: 2028, round: 'Second Round', teamFrom: 'Boston Celtics', swapOwner: null, swapOption: null, protections: '46-60', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'New York Knicks', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'New York Knicks', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'New York Knicks', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'New York Knicks', year: 2028, round: 'Second Round', teamFrom: null, swapOwner: 'Indiana Pacers, Phoenix Suns', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'New York Knicks', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'OKC, HOU, IND, MIA', rank: '3rd most favorable' },
  { teamOwner: 'New York Knicks', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'NYK, BRK, PHX', rank: 'Least favorable (if NYK and/or PHL 9-30 less favorable than BRK/PHX); otherwise 2nd most favorable' },
  { teamOwner: 'Oklahoma City Thunder', year: 2026, round: 'First Round', teamFrom: 'Los Angeles Clippers', swapOwner: null, swapOption: null, protections: null, pickNumber: 12, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2026, round: 'First Round', teamFrom: 'Philadelphia Sixers', swapOwner: null, swapOption: null, protections: null, pickNumber: 17, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2026, round: 'Second Round', teamFrom: 'Dallas Mavericks', swapOwner: null, swapOption: null, protections: null, pickNumber: 37, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2027, round: 'First Round', teamFrom: 'San Antonio Spurs', swapOwner: null, swapOption: null, protections: '17-30', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2028, round: 'First Round', teamFrom: null, swapOwner: 'Dallas Mavericks', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2028, round: 'Second Round', teamFrom: 'Utah Jazz', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2029, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2029, round: 'Second Round', teamFrom: 'Boston Celtics', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2030, round: 'Second Round', teamFrom: 'Denver Nuggets', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2030, round: 'Second Round', teamFrom: 'Houston Rockets', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2030, round: 'Second Round', teamFrom: 'Miami Heat', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2027, round: 'First Round', teamFrom: 'San Antonio Spurs', swapOwner: null, swapOption: null, protections: '1-16 to Sacramento Kings', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2027, round: 'Second Round', teamFrom: 'Sacramento Kings', swapOwner: null, swapOption: null, protections: 'if SAN 1-16 in 2027', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2028, round: 'First Round', teamFrom: 'Denver Nuggets', swapOwner: null, swapOption: null, protections: '6-30 if not already settled', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2029, round: 'First Round', teamFrom: 'Denver Nuggets', swapOwner: null, swapOption: null, protections: '6-30 if not already settled', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2029, round: 'Second Round', teamFrom: 'Denver Nuggets', swapOwner: null, swapOption: null, protections: 'if DEN has not conveyed a first potential 1st round pick to OKC by 2029', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2030, round: 'First Round', teamFrom: 'Denver Nuggets', swapOwner: null, swapOption: null, protections: '6-30 if not already settled and if DEN has conveyed a first potential 1st round pick to OKC by 2028', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2029, round: 'Second Round', teamFrom: null, swapOwner: 'Atlanta Hawks, Miami Heat', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: 'New Orleans Pelicans, Orlando Magic', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Oklahoma City Thunder', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'OKC, DEN 6-30, LAC', rank: 'Two most / more favorable' },
  { teamOwner: 'Oklahoma City Thunder', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'CHA, SAN', rank: 'Conditional: if SAN 1-16 in 2027' },
  { teamOwner: 'Orlando Magic', year: 2026, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 46, pickPool: null, rank: null },
  { teamOwner: 'Orlando Magic', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Orlando Magic', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: 'New Orleans Pelicans', protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Orlando Magic', year: 2030, round: 'Second Round', teamFrom: 'Milwaukee Bucks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Orlando Magic', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Orlando Magic', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Orlando Magic', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Orlando Magic', year: 2029, round: 'First Round', teamFrom: null, swapOwner: 'Memphis Grizzlies', swapOption: null, protections: '1-2', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Orlando Magic', year: 2028, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: 'Los Angeles Lakers, Washington Wizards', protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Orlando Magic', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'ORL, NOP', rank: 'More favorable' },
  { teamOwner: 'Philadelphia Sixers', year: 2026, round: 'First Round', teamFrom: 'Houston Rockets', swapOwner: null, swapOption: null, protections: null, pickNumber: 22, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2028, round: 'First Round', teamFrom: 'Los Angeles Clippers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2028, round: 'Second Round', teamFrom: 'Detroit Pistons', swapOwner: null, swapOption: null, protections: '56-60', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2028, round: 'Second Round', teamFrom: 'Golden State Warriors', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2028, round: 'Second Round', teamFrom: 'Milwaukee Bucks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2028, round: 'Second Round', teamFrom: 'Oklahoma City Thunder', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2029, round: 'First Round', teamFrom: null, swapOwner: 'Los Angeles Clippers', swapOption: null, protections: '1-3', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2029, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2030, round: 'Second Round', teamFrom: 'Washington Wizards', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: 'Memphis Grizzlies', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: 'Golden State Warriors, Phoenix Suns', protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Philadelphia Sixers', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: 'Phoenix Suns, Portland Trail Blazers', protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Phoenix Suns', year: 2026, round: 'Second Round', teamFrom: 'Philadelphia Sixers', swapOwner: null, swapOption: null, protections: null, pickNumber: 47, pickPool: null, rank: null },
  { teamOwner: 'Phoenix Suns', year: 2029, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Phoenix Suns', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: 'Frozen through 2027-28', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Phoenix Suns', year: 2027, round: 'First Round', teamFrom: null, swapOwner: 'Utah Jazz, Cleveland Cavaliers, Minnesota Timberwolves', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Phoenix Suns', year: 2030, round: 'First Round', teamFrom: null, swapOwner: 'Washington Wizards, Memphis Grizzlies', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Phoenix Suns', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'PHX, PHL 9-30, WAS, BRK', rank: 'Least favorable' },
  { teamOwner: 'Phoenix Suns', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'PHX, HOU', rank: 'Less favorable' },
  { teamOwner: 'Portland Trail Blazers', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Portland Trail Blazers', year: 2027, round: 'Second Round', teamFrom: 'Minnesota Timberwolves', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Portland Trail Blazers', year: 2028, round: 'First Round', teamFrom: null, swapOwner: 'Milwaukee Bucks', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Portland Trail Blazers', year: 2028, round: 'First Round', teamFrom: 'Orlando Magic', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Portland Trail Blazers', year: 2028, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Portland Trail Blazers', year: 2028, round: 'Second Round', teamFrom: 'Sacramento Kings', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Portland Trail Blazers', year: 2030, round: 'First Round', teamFrom: null, swapOwner: 'Milwaukee Bucks', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Portland Trail Blazers', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Portland Trail Blazers', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Portland Trail Blazers', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Portland Trail Blazers', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Portland Trail Blazers', year: 2029, round: 'Second Round', teamFrom: null, swapOwner: 'Indiana Pacers, Washington Wizards', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Portland Trail Blazers', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'POR, NOP', rank: 'Less favorable' },
  { teamOwner: 'Portland Trail Blazers', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'POR, BOS, MIL', rank: 'Most and Least favorable' },
  { teamOwner: 'Sacramento Kings', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 7, pickPool: null, rank: null },
  { teamOwner: 'Sacramento Kings', year: 2026, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 34, pickPool: null, rank: null },
  { teamOwner: 'Sacramento Kings', year: 2026, round: 'Second Round', teamFrom: 'Charlotte Hornets', swapOwner: null, swapOption: null, protections: null, pickNumber: 45, pickPool: null, rank: null },
  { teamOwner: 'Sacramento Kings', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Sacramento Kings', year: 2027, round: 'First Round', teamFrom: 'San Antonio Spurs', swapOwner: null, swapOption: null, protections: '1-16', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Sacramento Kings', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Sacramento Kings', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Sacramento Kings', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Sacramento Kings', year: 2031, round: 'First Round', teamFrom: null, swapOwner: 'San Antonio Spurs', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Sacramento Kings', year: 2031, round: 'First Round', teamFrom: 'Minnesota Timberwolves', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Sacramento Kings', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Sacramento Kings', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Sacramento Kings', year: 2027, round: 'First Round', teamFrom: 'San Antonio Spurs', swapOwner: null, swapOption: null, protections: '17-30 to Oklahoma City Thunder', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Sacramento Kings', year: 2027, round: 'Second Round', teamFrom: 'Charlotte Hornets', swapOwner: null, swapOption: null, protections: 'if SAN 17-30 in 2027', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2026, round: 'First Round', teamFrom: 'Atlanta Hawks', swapOwner: null, swapOption: null, protections: null, pickNumber: 20, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2026, round: 'Second Round', teamFrom: 'Utah Jazz', swapOwner: null, swapOption: null, protections: null, pickNumber: 35, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2026, round: 'Second Round', teamFrom: 'Portland Trail Blazers', swapOwner: null, swapOption: null, protections: null, pickNumber: 42, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2026, round: 'Second Round', teamFrom: 'Miami Heat', swapOwner: null, swapOption: null, protections: null, pickNumber: 44, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2027, round: 'First Round', teamFrom: 'Atlanta Hawks', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2028, round: 'First Round', teamFrom: null, swapOwner: 'Boston Celtics', swapOption: null, protections: '1', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2028, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2028, round: 'Second Round', teamFrom: 'Minnesota Timberwolves', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2028, round: 'Second Round', teamFrom: 'New Orleans Pelicans', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2029, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2029, round: 'Second Round', teamFrom: 'Los Angeles Clippers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2029, round: 'Second Round', teamFrom: 'New Orleans Pelicans', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2030, round: 'Second Round', teamFrom: 'Cleveland Cavaliers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2030, round: 'Second Round', teamFrom: 'Sacramento Kings', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2031, round: 'First Round', teamFrom: null, swapOwner: 'Sacramento Kings', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2031, round: 'Second Round', teamFrom: 'Sacramento Kings', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2028, round: 'Second Round', teamFrom: 'Boston Celtics', swapOwner: null, swapOption: null, protections: '31-45 if BOS 1 in 2028', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'San Antonio Spurs', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'SAN, OKC, HOU, IND, MIA', rank: 'More favorable of SAN vs (least favorable of OKC/HOU/IND/MIA)' },
  { teamOwner: 'San Antonio Spurs', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'SAN, DAL, MIN 2-30', rank: 'Most / more favorable' },
  { teamOwner: 'Toronto Raptors', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 19, pickPool: null, rank: null },
  { teamOwner: 'Toronto Raptors', year: 2026, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 50, pickPool: null, rank: null },
  { teamOwner: 'Toronto Raptors', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Toronto Raptors', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Toronto Raptors', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Toronto Raptors', year: 2028, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Toronto Raptors', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Toronto Raptors', year: 2029, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Toronto Raptors', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Toronto Raptors', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Toronto Raptors', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Toronto Raptors', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Utah Jazz', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 2, pickPool: null, rank: null },
  { teamOwner: 'Utah Jazz', year: 2027, round: 'Second Round', teamFrom: 'Denver Nuggets', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Utah Jazz', year: 2027, round: 'Second Round', teamFrom: 'Los Angeles Clippers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Utah Jazz', year: 2028, round: 'First Round', teamFrom: null, swapOwner: 'Cleveland Cavaliers', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Utah Jazz', year: 2028, round: 'Second Round', teamFrom: 'Cleveland Cavaliers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Utah Jazz', year: 2029, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Utah Jazz', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Utah Jazz', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Utah Jazz', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Utah Jazz', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Utah Jazz', year: 2032, round: 'Second Round', teamFrom: 'Cleveland Cavaliers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Utah Jazz', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: 'Boston Celtics, Orlando Magic', protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Utah Jazz', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: 'Boston Celtics, Cleveland Cavaliers', protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Utah Jazz', year: 2029, round: 'Second Round', teamFrom: 'Minnesota Timberwolves', swapOwner: null, swapOption: null, protections: 'if MIN does not convey 1st round pick to UTH in 2029', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Utah Jazz', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'UTH, CLE, MIN', rank: '2nd most favorable' },
  { teamOwner: 'Utah Jazz', year: 2028, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'DET 31-55, CHA, LAC, MIA, NYK', rank: 'Least favorable of (DET 31-55, less favorable of CHA/LAC, conditional MIA, NYK)' },
  { teamOwner: 'Utah Jazz', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'UTH, CLE, MIN 6-30', rank: 'Most / two most favorable' },
  { teamOwner: 'Utah Jazz', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'UTH, LAC', rank: 'Less favorable' },
  { teamOwner: 'Washington Wizards', year: 2026, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: 1, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2026, round: 'Second Round', teamFrom: 'Minnesota Timberwolves', swapOwner: null, swapOption: null, protections: null, pickNumber: 51, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2026, round: 'Second Round', teamFrom: 'Oklahoma City Thunder', swapOwner: null, swapOption: null, protections: null, pickNumber: 60, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2027, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2028, round: 'Second Round', teamFrom: 'Denver Nuggets', swapOwner: null, swapOption: null, protections: '34-60', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2029, round: 'Second Round', teamFrom: 'Los Angeles Lakers', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2031, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2031, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2032, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2032, round: 'Second Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2032, round: 'Second Round', teamFrom: 'Utah Jazz', swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2028, round: 'Second Round', teamFrom: 'Denver Nuggets', swapOwner: null, swapOption: null, protections: '31-33 to Denver Nuggets', pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2027, round: 'Second Round', teamFrom: null, swapOwner: 'Golden State Warriors, Phoenix Suns', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2030, round: 'Second Round', teamFrom: null, swapOwner: 'Phoenix Suns, Portland Trail Blazers', swapOption: null, protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2030, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: 'Phoenix Suns', protections: null, pickNumber: null, pickPool: null, rank: null },
  { teamOwner: 'Washington Wizards', year: 2028, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'WAS, BRK, PHL 9-30, PHX, MIL, POR', rank: 'Less favorable of (more favorable of WAS/least-or-less-favorable-of-BRK-PHL9-30-PHX) vs (less favorable of MIL/POR)' },
  { teamOwner: 'Washington Wizards', year: 2029, round: 'First Round', teamFrom: null, swapOwner: null, swapOption: null, protections: null, pickNumber: null, pickPool: 'POR, BOS, MIL', rank: '2nd most favorable' },
]

export function getPicksByTeam(teamName: string): DraftPick[] {
  return DRAFT_PICKS.filter(p => p.teamOwner === teamName)
}

export function getPicksByYear(year: number): DraftPick[] {
  return DRAFT_PICKS.filter(p => p.year === year)
}

export function getPicksByTeamAbbr(abbr: string): DraftPick[] {
  const fullName = Object.entries(TEAM_NAME_TO_ABBR).find(([, a]) => a === abbr)?.[0]
  if (!fullName) return []
  return getPicksByTeam(fullName)
}

export function getTeamAbbr(teamName: string): string {
  return TEAM_NAME_TO_ABBR[teamName] ?? teamName
}

export function getDraftPickPlayers(teamAbbr: string): Player[] {
  const picks = getPicksByTeamAbbr(teamAbbr)

  const sorted = [...picks].sort((a, b) => {
    if (a.year !== b.year) return a.year - b.year
    if (a.round === 'First Round' && b.round === 'Second Round') return -1
    if (a.round === 'Second Round' && b.round === 'First Round') return 1
    return 0
  })

  return sorted.map((pick, idx) => {
    const startSeasonStr = `${pick.year}-${String(pick.year + 1).slice(2)}` as Season
    const startIdx = SEASONS.indexOf(startSeasonStr)
    const salary: Partial<Record<Season, number>> = {}
    if (startIdx !== -1) {
      for (let i = startIdx; i < Math.min(startIdx + 4, SEASONS.length); i++) {
        salary[SEASONS[i]] = 5_000_000
      }
    }
    return {
      id: `draft-${pick.year}-${pick.round.replace(/ /g, '-')}-${teamAbbr}-${idx}`,
      name: `${pick.year} ${pick.round === 'First Round' ? 'First' : 'Second'} Round Pick`,
      team: teamAbbr,
      salary,
      options: {},
    } as Player
  })
}

export { TEAM_NAME_TO_ABBR }
