import { playerKey } from './player-key'

export type FreeAgentType = 'unrestricted' | 'restricted'
export type BirdRights = 'non-bird' | 'early-bird' | 'full-bird'

export interface FreeAgentPoolEntry {
  name: string
  priorTeam: string
  faType: FreeAgentType
  birdRights?: BirdRights
}

// Currently-unsigned free agents, sourced from RealGM's current_free_agents
// page (scripts/scrape/run.py::build_free_agent_pool). Distinct from
// player-data.ts: these players have no roster row anywhere in that file
// because no team currently employs them. Only valid for the season this
// scrape ran in — it's a snapshot of who's unsigned right now, not a
// projection of future free agency.
// GENERATED:START
export const FREE_AGENT_POOL: FreeAgentPoolEntry[] = [
  { name: 'Ochai Agbaji', priorTeam: 'BRK', faType: 'unrestricted' },
  { name: 'Alex Antetokounmpo', priorTeam: 'MIL', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Thanasis Antetokounmpo', priorTeam: 'MIL', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Adama-Alpha Bal', priorTeam: 'MEM', faType: 'unrestricted' },
  { name: 'Patrick Baldwin, Jr.', priorTeam: 'SAC', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Lonzo Ball', priorTeam: 'UTA', faType: 'unrestricted' },
  { name: 'Dalano Banton', priorTeam: 'BOS', faType: 'unrestricted' },
  { name: 'Nicolas Batum', priorTeam: 'LAC', faType: 'unrestricted', birdRights: 'early-bird' },
  { name: 'MarJon Beauchamp', priorTeam: 'PHI', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Jules Bernard', priorTeam: 'MIN', faType: 'unrestricted' },
  { name: 'Bismack Biyombo', priorTeam: 'SAS', faType: 'unrestricted', birdRights: 'early-bird' },
  { name: 'Leaky Black', priorTeam: 'WAS', faType: 'unrestricted' },
  { name: 'Buddy Boeheim', priorTeam: 'OKC', faType: 'unrestricted' },
  { name: 'Chris Boucher', priorTeam: 'UTA', faType: 'unrestricted' },
  { name: 'Tony Bradley', priorTeam: 'ATL', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Malaki Branham', priorTeam: 'CHO', faType: 'unrestricted' },
  { name: 'Darius Brown II', priorTeam: 'CLE', faType: 'unrestricted' },
  { name: 'Bruce Brown, Jr.', priorTeam: 'DEN', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Tyler Burton', priorTeam: 'MEM', faType: 'unrestricted' },
  { name: 'Kennedy Chandler', priorTeam: 'UTA', faType: 'unrestricted' },
  { name: 'Ulrich Chomche', priorTeam: 'TOR', faType: 'unrestricted' },
  { name: 'Amir Coffey', priorTeam: 'PHO', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Javonte Cooke', priorTeam: 'POR', faType: 'unrestricted' },
  { name: 'Sharife Cooper', priorTeam: 'WAS', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Seth Curry', priorTeam: 'GSW', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'N\'Faly Dante', priorTeam: 'ATL', faType: 'unrestricted' },
  { name: 'J.D. Davison', priorTeam: 'HOU', faType: 'unrestricted' },
  { name: 'DeMar DeRozan', priorTeam: 'SAC', faType: 'unrestricted' },
  { name: 'Nikola Djurisic', priorTeam: 'ATL', faType: 'unrestricted' },
  { name: 'Jalen Duren', priorTeam: 'DET', faType: 'restricted', birdRights: 'full-bird' },
  { name: 'Jesse Edwards', priorTeam: 'MIN', faType: 'unrestricted' },
  { name: 'Tyson Etienne', priorTeam: 'BRK', faType: 'unrestricted', birdRights: 'early-bird' },
  { name: 'Drew Eubanks', priorTeam: 'SAC', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Tosan Evbuomwan', priorTeam: 'CHO', faType: 'unrestricted' },
  { name: 'Dante Exum', priorTeam: 'WAS', faType: 'unrestricted' },
  { name: 'Trentyn Flowers', priorTeam: 'CHI', faType: 'unrestricted' },
  { name: 'Markelle Fultz', priorTeam: 'TOR', faType: 'unrestricted' },
  { name: 'Andersson Garcia', priorTeam: 'UTA', faType: 'unrestricted' },
  { name: 'Anthony Gill', priorTeam: 'WAS', faType: 'unrestricted', birdRights: 'full-bird' },
  { name: 'Eric Gordon', priorTeam: 'MEM', faType: 'unrestricted' },
  { name: 'Hayden Gray', priorTeam: 'UTA', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Jeff Green', priorTeam: 'HOU', faType: 'unrestricted', birdRights: 'full-bird' },
  { name: 'Mouhamadou Gueye', priorTeam: 'CHO', faType: 'unrestricted' },
  { name: 'James Harden', priorTeam: 'CLE', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Kevon Harris', priorTeam: 'HOU', faType: 'unrestricted' },
  { name: 'Killian Hayes', priorTeam: 'SAC', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Nigel Hayes-Davis', priorTeam: 'MIL', faType: 'unrestricted' },
  { name: 'Aaron Holiday', priorTeam: 'HOU', faType: 'unrestricted', birdRights: 'full-bird' },
  { name: 'Joe Ingles', priorTeam: 'MIN', faType: 'unrestricted', birdRights: 'early-bird' },
  { name: 'Jaden Ivey', priorTeam: 'CHI', faType: 'unrestricted' },
  { name: 'DeJon Jarreau', priorTeam: 'MEM', faType: 'unrestricted' },
  { name: 'DaQuan Jeffries', priorTeam: 'SAC', faType: 'unrestricted' },
  { name: 'Keshad Johnson', priorTeam: 'MIA', faType: 'unrestricted', birdRights: 'early-bird' },
  { name: 'Colby Jones', priorTeam: 'DET', faType: 'unrestricted' },
  { name: 'Curtis Jones', priorTeam: 'DEN', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Dillon Jones', priorTeam: 'NYK', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Johnny Juzang', priorTeam: 'MIN', faType: 'unrestricted' },
  { name: 'Trevor Keels', priorTeam: 'MIA', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Miles Kelly', priorTeam: 'DAL', faType: 'unrestricted' },
  { name: 'Tyreke Key', priorTeam: 'TOR', faType: 'unrestricted' },
  { name: 'Maxi Kleber', priorTeam: 'LAL', faType: 'unrestricted' },
  { name: 'Bobi Klintman', priorTeam: 'DET', faType: 'unrestricted' },
  { name: 'Jonathan Kuminga', priorTeam: 'ATL', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Skal Labissiere', priorTeam: 'WAS', faType: 'unrestricted' },
  { name: 'A.J. Lawson', priorTeam: 'TOR', faType: 'unrestricted', birdRights: 'early-bird' },
  { name: 'Isaiah Livers', priorTeam: 'PHO', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Chris Livingston', priorTeam: 'CLE', faType: 'unrestricted' },
  { name: 'Kevin Love', priorTeam: 'UTA', faType: 'unrestricted', birdRights: 'full-bird' },
  { name: 'Lawson Lovering', priorTeam: 'MEM', faType: 'unrestricted' },
  { name: 'Kyle Lowry', priorTeam: 'PHI', faType: 'unrestricted', birdRights: 'full-bird' },
  { name: 'Seth Lundy', priorTeam: 'LAC', faType: 'unrestricted' },
  { name: 'Kyle Mangas', priorTeam: 'SAS', faType: 'unrestricted' },
  { name: 'Tyrese Martin', priorTeam: 'PHI', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Bennedict Mathurin', priorTeam: 'LAC', faType: 'restricted', birdRights: 'full-bird' },
  { name: 'Bez Mbeng', priorTeam: 'UTA', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Mac McClung', priorTeam: 'CHI', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Kevin McCullar, Jr.', priorTeam: 'NYK', faType: 'unrestricted', birdRights: 'early-bird' },
  { name: 'Doug McDermott', priorTeam: 'SAC', faType: 'unrestricted', birdRights: 'early-bird' },
  { name: 'Emanuel Miller', priorTeam: 'SAS', faType: 'unrestricted' },
  { name: 'Wendell Moore, Jr.', priorTeam: 'DET', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Eli N\'Diaye', priorTeam: 'ATL', faType: 'unrestricted' },
  { name: 'Grant Nelson', priorTeam: 'BRK', faType: 'unrestricted' },
  { name: 'Georges Niang', priorTeam: 'MEM', faType: 'unrestricted' },
  { name: 'Miles Norris', priorTeam: 'BOS', faType: 'unrestricted' },
  { name: 'Josh Oduro', priorTeam: 'NOP', faType: 'unrestricted', birdRights: 'early-bird' },
  { name: 'Toby Okani', priorTeam: 'MEM', faType: 'unrestricted' },
  { name: 'Lachlan Olbrich', priorTeam: 'CHI', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Kelly Olynyk', priorTeam: 'SAS', faType: 'unrestricted', birdRights: 'full-bird' },
  { name: 'Norchad Omier', priorTeam: 'LAC', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Chris Paul', priorTeam: 'TOR', faType: 'unrestricted' },
  { name: 'Cameron Payne', priorTeam: 'PHI', faType: 'unrestricted' },
  { name: 'Sean Pedulla', priorTeam: 'LAC', faType: 'unrestricted' },
  { name: 'Drew Peterson', priorTeam: 'CHO', faType: 'unrestricted' },
  { name: 'Mason Plumlee', priorTeam: 'SAS', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Dwight Powell', priorTeam: 'DAL', faType: 'unrestricted', birdRights: 'full-bird' },
  { name: 'Duop Reath', priorTeam: 'ATL', faType: 'unrestricted' },
  { name: 'Antonio Reeves', priorTeam: 'CHO', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Nick Richards', priorTeam: 'CHI', faType: 'unrestricted' },
  { name: 'Kadary Richmond', priorTeam: 'WAS', faType: 'unrestricted' },
  { name: 'Orlando Robinson', priorTeam: 'ORL', faType: 'unrestricted' },
  { name: 'Jeremiah Robinson-Earl', priorTeam: 'DAL', faType: 'unrestricted' },
  { name: 'David Roddy', priorTeam: 'DEN', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Jackson Rowe', priorTeam: 'GSW', faType: 'unrestricted' },
  { name: 'Terry Rozier', priorTeam: 'MIA', faType: 'unrestricted' },
  { name: 'Hunter Sallis', priorTeam: 'PHI', faType: 'unrestricted' },
  { name: 'Payton Sandfort', priorTeam: 'OKC', faType: 'unrestricted' },
  { name: 'Dario Saric', priorTeam: 'DET', faType: 'unrestricted' },
  { name: 'Olivier Sarr', priorTeam: 'CLE', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Tre Scott', priorTeam: 'BRK', faType: 'unrestricted' },
  { name: 'Mark Sears', priorTeam: 'MIL', faType: 'unrestricted' },
  { name: 'Max Shulga', priorTeam: 'BOS', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Nick Smith, Jr.', priorTeam: 'LAL', faType: 'unrestricted' },
  { name: 'Malachi Smith', priorTeam: 'BRK', faType: 'unrestricted' },
  { name: 'Tyler Smith', priorTeam: 'DAL', faType: 'unrestricted' },
  { name: 'Isaiah Stevens', priorTeam: 'SAC', faType: 'unrestricted' },
  { name: 'Peter Suder', priorTeam: 'LAL', faType: 'unrestricted' },
  { name: 'Jahmyl Telfort', priorTeam: 'LAC', faType: 'unrestricted' },
  { name: 'Garrett Temple', priorTeam: 'TOR', faType: 'unrestricted', birdRights: 'full-bird' },
  { name: 'Dalen Terry', priorTeam: 'PHI', faType: 'unrestricted' },
  { name: 'Cam Thomas', priorTeam: 'MIL', faType: 'unrestricted' },
  { name: 'Ethan Thompson', priorTeam: 'IND', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Xavier Tillman, Sr.', priorTeam: 'CHO', faType: 'unrestricted', birdRights: 'full-bird' },
  { name: 'Drew Timme', priorTeam: 'LAL', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Alex Toohey', priorTeam: 'GSW', faType: 'unrestricted' },
  { name: 'Jacob Toppin', priorTeam: 'ATL', faType: 'unrestricted' },
  { name: 'Luke Travers', priorTeam: 'CLE', faType: 'unrestricted' },
  { name: 'Hunter Tyson', priorTeam: 'BRK', faType: 'unrestricted' },
  { name: 'Stanley Umude', priorTeam: 'SAS', faType: 'unrestricted' },
  { name: 'Jonas Valanciunas', priorTeam: 'DEN', faType: 'unrestricted' },
  { name: 'Gabe Vincent', priorTeam: 'ATL', faType: 'unrestricted', birdRights: 'full-bird' },
  { name: 'Keaton Wallace', priorTeam: 'ATL', faType: 'unrestricted', birdRights: 'early-bird' },
  { name: 'TyTy Washington, Jr.', priorTeam: 'LAC', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Lindy Waters III', priorTeam: 'SAS', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Trendon Watford', priorTeam: 'PHI', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Peyton Watson', priorTeam: 'DEN', faType: 'restricted', birdRights: 'full-bird' },
  { name: 'Blake Wesley', priorTeam: 'POR', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Russell Westbrook', priorTeam: 'SAC', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Dariq Whitehead', priorTeam: 'MEM', faType: 'unrestricted' },
  { name: 'Alondes Williams', priorTeam: 'WAS', faType: 'unrestricted' },
  { name: 'Brandon Williams', priorTeam: 'DAL', faType: 'unrestricted', birdRights: 'full-bird' },
  { name: 'Nate Williams, Jr.', priorTeam: 'GSW', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Vincent Williams, Jr.', priorTeam: 'UTA', faType: 'unrestricted' },
  { name: 'Malik Williams', priorTeam: 'ATL', faType: 'unrestricted' },
  { name: 'Lucas Williamson', priorTeam: 'MEM', faType: 'unrestricted' },
  { name: 'Isaiah Wong', priorTeam: 'CHO', faType: 'unrestricted' },
  { name: 'Guerschon Yabusele', priorTeam: 'CHI', faType: 'unrestricted' },
  { name: 'Cui Yongxi', priorTeam: 'BRK', faType: 'unrestricted' },
  { name: 'Jahmir Young', priorTeam: 'MIA', faType: 'unrestricted', birdRights: 'non-bird' },
  { name: 'Omer Yurtseven', priorTeam: 'GSW', faType: 'unrestricted' },
]
// GENERATED:END

const poolByKey = new Map(FREE_AGENT_POOL.map((fa) => [playerKey(fa.name), fa]))

export function getFreeAgentPoolEntry(playerName: string): FreeAgentPoolEntry | undefined {
  return poolByKey.get(playerKey(playerName))
}
